# Generated by Django 3.2.9 on 2021-11-07 17:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BakeryOwner', '0003_auto_20211107_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='id',
            field=models.BigAutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='ingredient',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='i1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='i1', to='BakeryOwner.ingredients', unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='i2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='i2', to='BakeryOwner.ingredients', unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='i3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='i3', to='BakeryOwner.ingredients', unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='i4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='i4', to='BakeryOwner.ingredients', unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='i5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='i5', to='BakeryOwner.ingredients', unique=True),
        ),
    ]
