# Generated by Django 3.2.9 on 2021-11-07 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BakeryOwner', '0004_auto_20211107_2240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredients',
            options={'verbose_name_plural': 'Ingredients'},
        ),
        migrations.AlterField(
            model_name='products',
            name='i1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='i1', to='BakeryOwner.ingredients', unique=True, verbose_name='Ingredients'),
        ),
        migrations.AlterField(
            model_name='products',
            name='i2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='i2', to='BakeryOwner.ingredients', unique=True, verbose_name='Ingredients'),
        ),
        migrations.AlterField(
            model_name='products',
            name='i3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='i3', to='BakeryOwner.ingredients', unique=True, verbose_name='Ingredients'),
        ),
        migrations.AlterField(
            model_name='products',
            name='i4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='i4', to='BakeryOwner.ingredients', unique=True, verbose_name='Ingredients'),
        ),
        migrations.AlterField(
            model_name='products',
            name='i5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='i5', to='BakeryOwner.ingredients', unique=True, verbose_name='Ingredients'),
        ),
    ]
